### ISSUE TITLE
Failed to start wsl-vpnkit.service: Interactive authentication required.

### ISSUE THREAD

**Issue by allenelguira16** [AmmarRahman/wsl-vpn#18]
Hello @AmmarRahman, there is a persisting issue regarding systemctl where it needs a Interactive authentication required.

I am using zsh for my shell

![image](https://user-images.githubusercontent.com/46128658/224001620-175a3fb2-df99-440a-af24-f07497b3fd6e.png)

If I manually run `sudo systemctl start wsl-vpnkit.service` it will work

**Comment by andyneff** [comment]
What OS are you trying to run this in? The command is normally (Not systemctl):

```
service wsl-vpnkit status > /dev/null || service wsl-vpnkit start
```

No sudo should be need for that.

**Comment by andyneff** [comment]
This only runs on Debian and Ubuntu. If you are using something else, you need to create an Ubuntu WSL and install it in there. 

**Only install this in _one_ WSL.**

In my case, I installed in the distro named `Ubuntu-20.04` so I added the following to all of my all my bashrc's (or zshrc in your case)

```bash
if [ -n "${WSL_INTEROP+set}" ] && \
   [ "${WSL_DISTRO_NAME}" != "Ubuntu-20.04" ] && \
   ! /mnt/c/Windows/System32/wsl.exe --cd / -d Ubuntu-20.04 service wsl-vpnkit status &>/dev/null; then
  /mnt/c/Windows/System32/wsl.exe --cd / -d Ubuntu-20.04 service wsl-vpnkit start
  # sudo equivalent
  # /mnt/c/Windows/System32/wsl.exe --cd / -d Ubuntu-20.04 --user root service wsl-vpnkit start
fi
```

**Comment by allenelguira16** [comment]
Yep, I forgot to add to zsh
will close this one, thanks~!
