### ISSUE TITLE
Always pull the latest version

### ISSUE THREAD

**Issue by andyneff** [AmmarRahman/wsl-vpn#7]
Update the setup script to always pull the latest release instead of having the hardcode the sha/release version in there

**Comment by andyneff** [comment]
An idea: https://gist.github.com/MarkTiedemann/c0adc1701f3f5c215fc2c2d5b1d5efd3

**Comment by AmmarRahman** [comment]
We have the WSLBIN_URL variable pointing at latest. My understanding this would automatically pull the latest binaries rather than a specific tag.  With npirelay, I would rather have it locked to version until manually tested

**Comment by andyneff** [comment]
Well, I'll be, I didn't even know that was possible! Good call! :D
